/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author rolim
 */
public class LoginView extends javax.swing.JFrame {
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        bnt_entrar = new javax.swing.JToggleButton();
        bnt_sair = new javax.swing.JToggleButton();
        bnt_cadastrar = new javax.swing.JToggleButton();
        bnt_divisao = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        img_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuario.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        txt_usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 150, 40));

        txt_senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_senha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 150, 40));

        bnt_entrar.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        bnt_entrar.setText("Entrar");
        bnt_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_entrarActionPerformed(evt);
            }
        });
        bnt_entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bnt_entrarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bnt_entrarKeyReleased(evt);
            }
        });
        getContentPane().add(bnt_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 100, 40));

        bnt_sair.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        bnt_sair.setText("Sair");
        bnt_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_sairActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 100, 40));

        bnt_cadastrar.setText("CADASTRAR");
        bnt_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 110, 40));

        bnt_divisao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criar Projeto", "Participar de Projeto", "Usuário" }));
        bnt_divisao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bnt_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_divisaoActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_divisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 150, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 520, 30));

        img_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LoginTela.png"))); // NOI18N
        getContentPane().add(img_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 520, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void bnt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_entrarActionPerformed
        // TODO add your handling code here:
 /*String textoLogin = txt_usuario.getText();
        String textoSenha = String.valueOf(txt_senha.getPassword());

        LoginView usuario = new LoginView();

        if(txt_usuario.()){
            // Ir para o Menu
            telaCadastro menu = new telaCadastro();
            menu.setVisible(true);
            this.dispose();
            
        }else{
             // Mensagem de ERRO de Usuario ou Senha;
             JOptionPane.showMessageDialog(null, "Login ou Senha invalidos.");
        }*/
    }//GEN-LAST:event_bnt_entrarActionPerformed

    private void bnt_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_divisaoActionPerformed
        // TODO add your handling code here:
        String divisao = bnt_divisao.getSelectedItem().toString();
        
    }//GEN-LAST:event_bnt_divisaoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void bnt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bnt_sairActionPerformed

    private void bnt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_cadastrarActionPerformed
        // TODO add your handling code here:
        new telaCadastro().setVisible(true);
    }//GEN-LAST:event_bnt_cadastrarActionPerformed

    private void bnt_entrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnt_entrarKeyPressed
        
        if(evt.getKeyCode() == evt.VK_ENTER){
            bnt_entrar.requestFocus();
        }
// TODO add your handling code here:
        
    }//GEN-LAST:event_bnt_entrarKeyPressed

    private void bnt_entrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnt_entrarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_entrarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bnt_cadastrar;
    private javax.swing.JComboBox<String> bnt_divisao;
    private javax.swing.JToggleButton bnt_entrar;
    private javax.swing.JToggleButton bnt_sair;
    private javax.swing.JLabel img_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

    private static class press {

        public press() {
        }
    }
}